### ISSUE TITLE
Is it ok get an Authentication object from JWT Claims instead of a Database?

### ISSUE THREAD

**Issue by wonsuc** [hantsy/spring-webmvc-jwt-sample#10]
From the `JwtTokenAuthenticationFilter` class, it checks every request's token and validates if it's correct.

And then it retrieves an `Authentication` object from Database and sets it to `SecurityContextHolder` like the below code.

```
Authentication auth = jwtTokenProvider.getAuthentication(token);
if (auth != null) {
    SecurityContextHolder.getContext().setAuthentication(auth);
}
```

However, my project's system uses another service API to login instead of directly getting user data from the Database.

It takes over seconds to log in or communicate to the API, so to create `Authentication` object for every request, I can't use the API to get user data.

My question is how do you think if I put user data into JWT Claims, and parse them to create `Authentication` object and set it to `SecurityContextHolder`?

My problem is user data is not in the database, it's at a different layer like 3rd party service API.

Thanks for providing great source codes.

**Comment by hantsy** [comment]
The codes are refreshed, now it is building Authentication from jwt token directly. @wonsuc

**Comment by hantsy** [comment]
The core of  handling jwt is aligned with another project: https://github.com/hantsy/spring-reactive-jwt-sample, I used the same codes to jwt token processing.

**Comment by hantsy** [comment]
The core of  handling jwt is aligned with another project: https://github.com/hantsy/spring-reactive-jwt-sample, I used the same codes to jwt token processing.

**Comment by wonsuc** [comment]
Thank you this is a great solution!
Can I ask one more question? It will be the last question.
I will post it with the new issue article.
