### ISSUE TITLE
How can I refresh token smoothly?

### ISSUE THREAD

**Issue by wonsuc** [hantsy/spring-webmvc-jwt-sample#11]
With OAuth 2.0 spec, there's a 'refresh token'.  
Since there's no OAuth resource server, there's no `refresh token` neither.  
Currently, I'm just showing a popup window that your `token` is expired, please log in again.  
But this means users need to log in every time when the `token` is expired.  (like every 30 minutes)
I use `jwt-decode` library to decode `token` from the client-side to check if the token is already expired and show a popup window.  
Is there any way I can do it from the client-side like when the `token` is expired sending some request to update `token` before sending a real request which is about the action what the user actually tried?  
Or if the last request time was in 30 minutes, extend the `token` expiration time 30 minutes more...  
I literally can find out the solution, can you give me some tips?
Thanks for many helps.

**Comment by MrNocTV** [comment]
What client side framework are you using? 

With Angular, you can do it using an `interceptor`.

**Comment by hantsy** [comment]
A classic refresh token flow.

1. When a user is authenticated, generated a fresh token along with the token. The token for refresh has a longer expiration date.
2. In the frontend, when a token is expired, use the refresh_token to access a */refresh_token* like URL to get the new token and refresh token.
3. In the backend, you have to handle refresh_token and recreate the token and refresh_token.

But if you like to use this flow. I suggest using a standalone IDP service is better, eg. Okta,  auth0.net, Keycloak, etc.

**Comment by hantsy** [comment]
@MrNocTV  Yeah, Http interceptor is a good place to handle token-related work.

https://github.com/hantsy/angular-spring-reactive-sample/blob/master/client/src/app/core/auth-inteceptor.ts

But if you are using a mature solution like Okta, it has its own client SDK, including Angular support to simplify the work.

**Comment by wonsuc** [comment]
> 어떤 클라이언트 측 프레임 워크를 사용하고 있습니까?
> 
> Angular를 사용하면 `interceptor`.

Currently I'm using `Axios` with `React.js`.
