### ISSUE TITLE
Logout part

### ISSUE THREAD

**Issue by markociglar** [hantsy/spring-webmvc-jwt-sample#8]
Thank you for sharing this piece of code. It helps me a lot.
Do you have implementation for logout part?

**Comment by hantsy** [comment]
For spa frontend, there is no need to care about the logout, just remove the token in the localStorage is ok. If you want to log out in the backend, make sure you have logged in,(thus there is a none null session existed),  the /logout endpoint is protected in my sample.

Hantsy Bai
Self-employed technical consultant, solution architect and full-stack developer
LinkedIN:  https://www.linkedin.com/in/hantsy
Github: https://github.com/hantsy
Blog:  https://medium.com/@hantsy

From: markociglar
Sent: Saturday, April 18, 2020 2:25 AM
To: hantsy/springboot-jwt-sample
Cc: Subscribed
Subject: [hantsy/springboot-jwt-sample] Logout part (#8)

Thank you for sharing this piece of code. It helps me a lot.
Do you implementation for logout part?
