### ISSUE TITLE
Is this code still modern?

### ISSUE THREAD

**Issue by wonsuc** [hantsy/spring-webmvc-jwt-sample#9]
It's already 3 years passed since this code was written.

I wonder if there is any new official way to achieve this via Spring Security SDK.

Thank you.

**Comment by hantsy** [comment]
No official solution like this exactly.  

Spring Security 5 has built-in OAuth2 and OIDC support, it is better to work with an existing IDP service, such as Keycloak,  auth0.net, okta, etc. Of course, this is more ideal for most SAAS applications.
